import PDFDocument from 'pdfkit';

const formatCurrency = (amount, currency = 'INR') =>
  new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency,
  }).format(amount);

const formatAddress = (user) => [user.address, user.city, user.zip].filter(Boolean).join(', ') || 'Not provided';

export const buildInvoicePdfBuffer = async ({ invoice, order }) =>
  new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 48 });
    const chunks = [];

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const currency = invoice.pricing.currency || order.payment.currency || 'INR';

    doc
      .fontSize(24)
      .text('Art-Case Invoice', { align: 'left' })
      .moveDown(0.3)
      .fontSize(10)
      .fillColor('#6b7280')
      .text(`Invoice Number: ${invoice.invoiceNumber}`)
      .text(`Order ID: ${invoice.orderId}`)
      .text(`Generated On: ${new Date(invoice.pdf.generatedAt || Date.now()).toLocaleString('en-IN')}`)
      .moveDown(1.5);

    doc
      .fillColor('#111827')
      .fontSize(14)
      .text('Customer Details')
      .moveDown(0.4)
      .fontSize(10)
      .text(`Name: ${invoice.user.name}`)
      .text(`Email: ${invoice.user.email}`)
      .text(`Phone: ${invoice.user.phone || 'Not provided'}`)
      .text(`Address: ${formatAddress(invoice.user)}`)
      .moveDown(1.2);

    doc
      .fontSize(14)
      .text('Payment Details')
      .moveDown(0.4)
      .fontSize(10)
      .text(`Payment Method: ${invoice.payment.method}`)
      .text(`Payment Status: ${invoice.payment.status}`)
      .text(`Razorpay Order ID: ${invoice.payment.razorpayOrderId || 'Not available'}`)
      .text(`Razorpay Payment ID: ${invoice.payment.razorpayPaymentId || 'Not available'}`)
      .moveDown(1.2);

    doc.fontSize(14).text('Items').moveDown(0.5);
    const startX = doc.x;
    const qtyX = 340;
    const amountX = 430;

    doc.fontSize(10).fillColor('#6b7280');
    doc.text('Description', startX, doc.y);
    doc.text('Qty', qtyX, doc.y - 12);
    doc.text('Amount', amountX, doc.y - 12);
    doc.moveDown(0.5).strokeColor('#d1d5db').moveTo(startX, doc.y).lineTo(540, doc.y).stroke().moveDown(0.5);

    invoice.items.forEach((item) => {
      const rowY = doc.y;
      doc.fillColor('#111827').text(item.title, startX, rowY, { width: 260 });
      doc.fillColor('#6b7280').text(item.category || '-', startX, doc.y + 2, { width: 260 });
      doc.fillColor('#111827').text(String(item.quantity), qtyX, rowY);
      doc.text(formatCurrency(item.lineTotal, currency), amountX, rowY);
      doc.moveDown(1.2);
    });

    doc.moveDown(0.3).strokeColor('#d1d5db').moveTo(startX, doc.y).lineTo(540, doc.y).stroke().moveDown(0.8);
    doc.fontSize(10).fillColor('#111827');
    doc.text(`Subtotal: ${formatCurrency(invoice.pricing.subtotal, currency)}`, { align: 'right' });
    doc.text(`Discount: ${formatCurrency(invoice.pricing.discount, currency)}`, { align: 'right' });
    doc.text(`Shipping: ${formatCurrency(invoice.pricing.shipping, currency)}`, { align: 'right' });
    doc.fontSize(12).text(`Total: ${formatCurrency(invoice.pricing.total, currency)}`, { align: 'right' });
    doc.moveDown(1.5);

    if (order.orderKind === 'commission' && order.commissionDetails) {
      doc.fontSize(14).text('Commission Notes').moveDown(0.4);
      doc.fontSize(10).fillColor('#111827').text(`Artwork Type: ${order.commissionDetails.artworkType || 'Custom commission'}`);
      doc.text(`Size Details: ${order.commissionDetails.sizeDetails || 'Not provided'}`);
      doc.text(`Brief: ${order.commissionDetails.description || 'No description provided.'}`);
      if (order.commissionDetails.adminNotes) {
        doc.text(`Admin Notes: ${order.commissionDetails.adminNotes}`);
      }
      doc.moveDown(1);
    }

    doc.fillColor('#6b7280').fontSize(10).text('This invoice is generated by Art-Case and serves as your order receipt.', {
      align: 'center',
    });

    doc.end();
  });
